import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import Map, { Layer, Marker, NavigationControl, Popup, Source, type MapLayerMouseEvent, type ViewStateChangeEvent } from 'react-map-gl/maplibre';
import 'maplibre-gl/dist/maplibre-gl.css';
import './styles.css';

type Location = { code: string; name: string; fullName: string; level: string };
type Analysis = { id: string; locationCode: string; locationName: string; riskLabel: 'LOW'|'MODERATE'|'HIGH'|'VERY_HIGH'; decisionStatus: string; timeWindow: string; confidence: string; latitude: number; longitude: number; reportToken?: string };
const mapStyle = 'https://tiles.openfreemap.org/styles/liberty'; // Free development tiles only; production provider requires human confirmation.
const label: Record<string, string> = { LOW: 'Rendah', MODERATE: 'Sedang', HIGH: 'Tinggi', VERY_HIGH: 'Sangat Tinggi' };
const shape: Record<string, string> = { LOW: '●', MODERATE: '▲', HIGH: '■', VERY_HIGH: '◆!' };

async function api<T>(url: string): Promise<T> { const response = await fetch(url); if (!response.ok) throw new Error((await response.json()).error?.message ?? 'Permintaan gagal'); return response.json(); }

function TextLocationPicker({ onSelect }: { onSelect: (location: Location) => void }) {
  const levels = ['adm1', 'adm2', 'adm3', 'adm4']; const names = ['Provinsi', 'Kabupaten/Kota', 'Kecamatan', 'Desa/Kelurahan'];
  const [selected, setSelected] = useState<(string | undefined)[]>([]); const [items, setItems] = useState<Record<string, Location[]>>({});
  useEffect(() => { const index = selected.length; if (index >= levels.length) return; const parent = selected[index - 1]; const url = `/api/v1/locations?level=${levels[index]}${parent ? `&parentCode=${encodeURIComponent(parent)}` : ''}`; void api<Location[]>(url).then((rows) => setItems((old) => ({ ...old, [levels[index]]: rows }))).catch(() => setItems((old) => ({ ...old, [levels[index]]: [] }))); }, [selected]);
  const choose = (index: number, value: string) => { const item = items[levels[index]]?.find((candidate) => candidate.code === value); if (!item) return; setSelected((old) => [...old.slice(0, index), value]); onSelect(item); };
  return <div className="dropdowns" aria-label="Pemilih lokasi tekstual">{levels.map((level, index) => <label key={level}>{names[index]}<select value={selected[index] ?? ''} disabled={index > selected.length} onChange={(event) => choose(index, event.target.value)}><option value="">Pilih…</option>{(items[level] ?? []).map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}</select></label>)}</div>;
}

function supportsWebgl2() { const canvas = document.createElement('canvas'); return Boolean(canvas.getContext('webgl2')); }

export function LocationPickerMap({ onSelect }: { onSelect: (location: Location) => void }) {
  const [view, setView] = useState({ longitude: 117, latitude: -2, zoom: 4.5 }); const [mapFailed, setMapFailed] = useState(() => !supportsWebgl2()); const [query, setQuery] = useState(''); const [results, setResults] = useState<Location[]>([]); const [selected, setSelected] = useState<Location | null>(null); const [boundary, setBoundary] = useState<unknown>();
  const select = useCallback(async (location: Location) => { setSelected(location); onSelect(location); try { setBoundary(await api(`/api/v1/locations/${encodeURIComponent(location.code)}/boundary`)); } catch { setBoundary(undefined); } }, [onSelect]);
  const click = async (event: MapLayerMouseEvent) => { try { const result = await api<Location>(`/api/v1/locations/resolve?lat=${event.lngLat.lat}&lng=${event.lngLat.lng}`); await select(result); } catch { setBoundary(undefined); } };
  useEffect(() => { if (query.trim().length < 2) { setResults([]); return; } const timer = window.setTimeout(() => void api<Location[]>(`/api/v1/locations/search?q=${encodeURIComponent(query)}&viewportLat=${view.latitude}&viewportLng=${view.longitude}`).then(setResults).catch(() => setResults([])), 250); return () => window.clearTimeout(timer); }, [query, view]);
  return <section className="picker"><div className="map-toolbar"><strong>Pilih lokasi operasional</strong><div className="search"><input aria-label="Cari lokasi" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari desa, kecamatan…" />{results.length > 0 && <ul>{results.map((result) => <li key={result.code}><button onClick={() => { setView({ longitude: 117, latitude: -2, zoom: 7 }); void select(result); setResults([]); }}>{result.name}<small>{result.fullName}</small></button></li>)}</ul>}</div></div>{mapFailed ? <div className="map-fallback"><p>Peta tidak tersedia. Gunakan pemilihan teks yang setara.</p><TextLocationPicker onSelect={select} /></div> : <Map {...view} onMove={(e: ViewStateChangeEvent) => setView(e.viewState)} onClick={click} onError={() => setMapFailed(true)} mapStyle={mapStyle} style={{ height: 390 }}><NavigationControl position="bottom-right" />{boundary && <Source id="selected-boundary" type="geojson" data={boundary as any}><Layer id="selected-boundary-fill" type="fill" paint={{ 'fill-color': '#22c55e', 'fill-opacity': 0.22 }} /><Layer id="selected-boundary-line" type="line" paint={{ 'line-color': '#16a34a', 'line-width': 3 }} /></Source>}</Map>}<div className="picker-footer"><button className="tab active" onClick={() => setMapFailed(false)}>Peta</button><span aria-hidden="true">atau</span><details><summary className="tab">Dropdown teks</summary><TextLocationPicker onSelect={select} /></details>{selected && <span className="precision">Presisi: {selected.level === 'adm4' ? 'Desa/Kelurahan' : 'Kecamatan'} ({selected.level})</span>}</div></section>;
}

export function TrackingMap({ analyses }: { analyses: Analysis[] }) {
  const [selected, setSelected] = useState<Analysis | null>(null); const [heatmap, setHeatmap] = useState(false); const [mapFailed, setMapFailed] = useState(() => !supportsWebgl2());
  const geojson = useMemo(() => ({ type: 'FeatureCollection', features: analyses.map((a) => ({ type: 'Feature', geometry: { type: 'Point', coordinates: [a.longitude, a.latitude] }, properties: { hazardScore: a.riskLabel === 'VERY_HIGH' ? 90 : a.riskLabel === 'HIGH' ? 70 : 40 } })) }), [analyses]);
  return <section className="tracking"><div className="tracking-map">{mapFailed ? <p className="map-fallback">Peta gagal dimuat. Data tetap tersedia pada daftar di samping.</p> : <Map initialViewState={{ longitude: 117, latitude: -2, zoom: 4.5 }} mapStyle={mapStyle} onError={() => setMapFailed(true)}><NavigationControl />{heatmap && <Source id="hazard" type="geojson" data={geojson as any}><Layer id="hazard-layer" type="heatmap" paint={{ 'heatmap-weight': ['get', 'hazardScore'], 'heatmap-radius': 30, 'heatmap-opacity': .65 }} /></Source>}{analyses.map((analysis) => <Marker key={analysis.id} longitude={analysis.longitude} latitude={analysis.latitude} anchor="bottom"><button className={`marker risk-${analysis.riskLabel.toLowerCase()}`} aria-label={`${label[analysis.riskLabel]} — ${analysis.locationName}`} onClick={() => setSelected(analysis)}>{shape[analysis.riskLabel]}</button></Marker>)}{selected && <Popup longitude={selected.longitude} latitude={selected.latitude} onClose={() => setSelected(null)} closeOnClick={false}><strong>{label[selected.riskLabel]} — {selected.locationName}</strong><p>{selected.decisionStatus}<br />{selected.timeWindow}<br />Confidence: {selected.confidence}</p>{selected.reportToken && <a href={`/api/v1/reports/${selected.reportToken}`}>Lihat laporan lengkap</a>}</Popup>}</Map>}</div><aside className="tracking-panel"><label className="toggle"><input type="checkbox" checked={heatmap} onChange={(e) => setHeatmap(e.target.checked)} /> Tampilkan heatmap hazard</label><p className="caption">Heatmap = agregasi HAZARD CUACA, bukan skor risiko proyek.</p><h2>Analisis aktif</h2><ul className="analysis-list" aria-label="Daftar analisis aktif">{analyses.map((a) => <li key={a.id}><button onClick={() => setSelected(a)}><span className={`swatch risk-${a.riskLabel.toLowerCase()}`}>{shape[a.riskLabel]}</span><span><strong>{label[a.riskLabel]} — {a.locationName}</strong><small>{a.decisionStatus} · {a.timeWindow} · Confidence {a.confidence}</small></span></button></li>)}</ul></aside></section>;
}

const demo: Analysis[] = [
  { id: 'a1', locationCode: 'DUMMY-KEL-1', locationName: 'Kelurahan Barat', riskLabel: 'LOW', decisionStatus: 'PROCEED', timeWindow: '08:00–10:00', confidence: 'HIGH', latitude: 0, longitude: -0.01 },
  { id: 'a2', locationCode: 'DUMMY-KEL-2', locationName: 'Kelurahan Timur', riskLabel: 'MODERATE', decisionStatus: 'PROCEED_WITH_MITIGATION', timeWindow: '10:00–12:00', confidence: 'MEDIUM', latitude: 0, longitude: 0.01 },
  { id: 'a3', locationCode: 'DUMMY-KEC', locationName: 'Kecamatan Dummy', riskLabel: 'HIGH', decisionStatus: 'DEFER', timeWindow: '13:00–15:00', confidence: 'MEDIUM', latitude: 0.01, longitude: 0 },
  { id: 'a4', locationCode: 'DUMMY-KAB', locationName: 'Kabupaten Dummy', riskLabel: 'VERY_HIGH', decisionStatus: 'NOT_RECOMMENDED', timeWindow: '16:00–18:00', confidence: 'LOW', latitude: -0.01, longitude: 0 },
];
function App() { const [picked, setPicked] = useState<Location | null>(null); return <main><header><p className="eyebrow">WEATHEROPS · FASE 6</p><h1>Peta operasional</h1><p className="lede">Peta adalah alat bantu input dan visualisasi. Backend tetap satu-satunya otoritas skor.</p></header><LocationPickerMap onSelect={setPicked} />{picked && <p className="selected">Lokasi dipilih: <strong>{picked.fullName}</strong> · {picked.code}</p>}<TrackingMap analyses={demo} /></main> }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);