import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import Map, { Layer, Marker, NavigationControl, Popup, Source, type MapLayerMouseEvent, type ViewStateChangeEvent } from 'react-map-gl/maplibre';
import 'maplibre-gl/dist/maplibre-gl.css';
import './styles.css';

type Location = { code: string; name: string; fullName: string; level: string };
type Analysis = { id: string; locationCode: string; locationName: string; riskLabel: 'LOW'|'MODERATE'|'HIGH'|'VERY_HIGH'; decisionStatus: string; timeWindow: string; confidence: string; latitude: number; longitude: number; reportToken?: string };
const mapStyle = 'https://tiles.openfreemap.org/styles/liberty'; // Free development tiles only; production provider requires human confirmation.
const label: Record<string, string> = { LOW: 'Rendah', MODERATE: 'Sedang', HIGH: 'Tinggi', VERY_HIGH: 'Sangat Tinggi' };
const shape: Record<string, string> = { LOW: '●', MODERATE: '▲', HIGH: '■', VERY_HIGH: '◆!' };

async function api<T>(url: string): Promise<T> { const response = await fetch(url); if (!response.ok) throw new Error((await response.json()).error?.message ?? 'Permintaan gagal'); return response.json(); }

function TextLocationPicker({ onSelect }: { onSelect: (location: Location) => void }) {
  const levels = ['adm1', 'adm2', 'adm3', 'adm4']; const names = ['Provinsi', 'Kabupaten/Kota', 'Kecamatan', 'Desa/Kelurahan'];
  const [selected, setSelected] = useState<(string | undefined)[]>([]); const [items, setItems] = useState<Record<string, Location[]>>({});
  useEffect(() => { const index = selected.length; if (index >= levels.length) return; const parent = selected[index - 1]; const url = `/api/v1/locations?level=${levels[index]}${parent ? `&parentCode=${encodeURIComponent(parent)}` : ''}`; void api<Location[]>(url).then((rows) => setItems((old) => ({ ...old, [levels[index]]: rows }))).catch(() => setItems((old) => ({ ...old, [levels[index]]: [] }))); }, [selected]);
  const choose = (index: number, value: string) => { const item = items[levels[index]]?.find((candidate) => candidate.code === value); if (!item) return; setSelected((old) => [...old.slice(0, index), value]); onSelect(item); };
  return <div className="dropdowns" aria-label="Pemilih lokasi tekstual">{levels.map((level, index) => <label key={level}>{names[index]}<select value={selected[index] ?? ''} disabled={index > selected.length} onChange={(event) => choose(index, event.target.value)}><option value="">Pilih…</option>{(items[level] ?? []).map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}</select></label>)}</div>;
}

function supportsWebgl2() { const canvas = document.createElement('canvas'); return Boolean(canvas.getContext('webgl2')); }

export function LocationPickerMap({ onSelect }: { onSelect: (location: Location) => void }) {
  const [view, setView] = useState({ longitude: 117, latitude: -2, zoom: 4.5 }); const [mapFailed, setMapFailed] = useState(() => !supportsWebgl2()); const [query, setQuery] = useState(''); const [results, setResults] = useState<Location[]>([]); const [selected, setSelected] = useState<Location | null>(null); const [boundary, setBoundary] = useState<unknown>();
  const select = useCallback(async (location: Location) => { setSelected(location); onSelect(location); try { setBoundary(await api(`/api/v1/locations/${encodeURIComponent(location.code)}/boundary`)); } catch { setBoundary(undefined); } }, [onSelect]);
  const click = async (event: MapLayerMouseEvent) => { try { const result = await api<Location>(`/api/v1/locations/resolve?lat=${event.lngLat.lat}&lng=${event.lngLat.lng}`); await select(result); } catch { setBoundary(undefined); } };
  useEffect(() => { if (query.trim().length < 2) { setResults([]); return; } const timer = window.setTimeout(() => void api<Location[]>(`/api/v1/locations/search?q=${encodeURIComponent(query)}&viewportLat=${view.latitude}&viewportLng=${view.longitude}`).then(setResults).catch(() => setResults([])), 250); return () => window.clearTimeout(timer); }, [query, view]);
  return <section className="picker"><div className="map-toolbar"><strong>Pilih lokasi operasional</strong><div className="search"><input aria-label="Cari lokasi" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari desa, kecamatan…" />{results.length > 0 && <ul>{results.map((result) => <li key={result.code}><button onClick={() => { setView({ longitude: 117, latitude: -2, zoom: 7 }); void select(result); setResults([]); }}>{result.name}<small>{result.fullName}</small></button></li>)}</ul>}</div></div>{mapFailed ? <div className="map-fallback"><p>Peta tidak tersedia. Gunakan pemilihan teks yang setara.</p><TextLocationPicker onSelect={select} /></div> : <Map {...view} onMove={(e: ViewStateChangeEvent) => setView(e.viewState)} onClick={click} onError={() => setMapFailed(true)} mapStyle={mapStyle} style={{ height: 390 }}><NavigationControl position="bottom-right" />{boundary && <Source id="selected-boundary" type="geojson" data={boundary as any}><Layer id="selected-boundary-fill" type="fill" paint={{ 'fill-color': '#22c55e', 'fill-opacity': 0.22 }} /><Layer id="selected-boundary-line" type="line" paint={{ 'line-color': '#16a34a', 'line-width': 3 }} /></Source>}</Map>}<div className="picker-footer"><button className="tab active" onClick={() => setMapFailed(false)}>Peta</button><span aria-hidden="true">atau</span><details><summary className="tab">Dropdown teks</summary><TextLocationPicker onSelect={select} /></details>{selected && <span className="precision">Presisi: {selected.level === 'adm4' ? 'Desa/Kelurahan' : 'Kecamatan'} ({selected.level})</span>}</div></section>;
}

export function TrackingMap({ analyses }: { analyses: Analysis[] }) {
  const [selected, setSelected] = useState<Analysis | null>(null); const [heatmap, setHeatmap] = useState(false); const [mapFailed, setMapFailed] = useState(() => !supportsWebgl2());
  const geojson = useMemo(() => ({ type: 'FeatureCollection', features: analyses.map((a) => ({ type: 'Feature', geometry: { type: 'Point', coordinates: [a.longitude, a.latitude] }, properties: { hazardScore: a.riskLabel === 'VERY_HIGH' ? 90 : a.riskLabel === 'HIGH' ? 70 : 40 } })) }), [analyses]);
  return <section className="tracking"><div className="tracking-map">{mapFailed ? <p className="map-fallback">Peta gagal dimuat. Data tetap tersedia pada daftar di samping.</p> : <Map initialViewState={{ longitude: 117, latitude: -2, zoom: 4.5 }} mapStyle={mapStyle} onError={() => setMapFailed(true)}><NavigationControl />{heatmap && <Source id="hazard" type="geojson" data={geojson as any}><Layer id="hazard-layer" type="heatmap" paint={{ 'heatmap-weight': ['get', 'hazardScore'], 'heatmap-radius': 30, 'heatmap-opacity': .65 }} /></Source>}{analyses.map((analysis) => <Marker key={analysis.id} longitude={analysis.longitude} latitude={analysis.latitude} anchor="bottom"><button className={`marker risk-${analysis.riskLabel.toLowerCase()}`} aria-label={`${label[analysis.riskLabel]} — ${analysis.locationName}`} onClick={() => setSelected(analysis)}>{shape[analysis.riskLabel]}</button></Marker>)}{selected && <Popup longitude={selected.longitude} latitude={selected.latitude} onClose={() => setSelected(null)} closeOnClick={false}><strong>{label[selected.riskLabel]} — {selected.locationName}</strong><p>{selected.decisionStatus}<br />{selected.timeWindow}<br />Confidence: {selected.confidence}</p>{selected.reportToken && <a href={`/api/v1/reports/${selected.reportToken}`}>Lihat laporan lengkap</a>}</Popup>}</Map>}</div><aside className="tracking-panel"><label className="toggle"><input type="checkbox" checked={heatmap} onChange={(e) => setHeatmap(e.target.checked)} /> Tampilkan heatmap hazard</label><p className="caption">Heatmap = agregasi HAZARD CUACA, bukan skor risiko proyek.</p><h2>Analisis aktif</h2><ul className="analysis-list" aria-label="Daftar analisis aktif">{analyses.map((a) => <li key={a.id}><button onClick={() => setSelected(a)}><span className={`swatch risk-${a.riskLabel.toLowerCase()}`}>{shape[a.riskLabel]}</span><span><strong>{label[a.riskLabel]} — {a.locationName}</strong><small>{a.decisionStatus} · {a.timeWindow} · Confidence {a.confidence}</small></span></button></li>)}</ul></aside></section>;
}

const demo: Analysis[] = [
  { id: 'a1', locationCode: 'DUMMY-KEL-1', locationName: 'Kelurahan Barat', riskLabel: 'LOW', decisionStatus: 'PROCEED', timeWindow: '08:00–10:00', confidence: 'HIGH', latitude: 0, longitude: -0.01 },
  { id: 'a2', locationCode: 'DUMMY-KEL-2', locationName: 'Kelurahan Timur', riskLabel: 'MODERATE', decisionStatus: 'PROCEED_WITH_MITIGATION', timeWindow: '10:00–12:00', confidence: 'MEDIUM', latitude: 0, longitude: 0.01 },
  { id: 'a3', locationCode: 'DUMMY-KEC', locationName: 'Kecamatan Dummy', riskLabel: 'HIGH', decisionStatus: 'DEFER', timeWindow: '13:00–15:00', confidence: 'MEDIUM', latitude: 0.01, longitude: 0 },
  { id: 'a4', locationCode: 'DUMMY-KAB', locationName: 'Kabupaten Dummy', riskLabel: 'VERY_HIGH', decisionStatus: 'NOT_RECOMMENDED', timeWindow: '16:00–18:00', confidence: 'LOW', latitude: -0.01, longitude: 0 },
];
function App() {
  const [picked, setPicked] = useState<Location | null>(null);
  const [dark, setDark] = useState(() => localStorage.getItem('weatherops-theme') !== 'light');
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => {
    document.documentElement.dataset.theme = dark ? 'dark' : 'light';
    localStorage.setItem('weatherops-theme', dark ? 'dark' : 'light');
  }, [dark]);
  return <div className="site-shell">
    <nav className="nav">
      <a className="brand" href="#" aria-label="WeatherOps home"><span className="brand-mark"><span>W</span></span><span>weather<span className="brand-muted">ops</span></span></a>
      <div className={`nav-links ${menuOpen ? 'open' : ''}`}><a href="#platform" onClick={() => setMenuOpen(false)}>Platform</a><a href="#how-it-works" onClick={() => setMenuOpen(false)}>How it works</a><a href="#trust" onClick={() => setMenuOpen(false)}>Trust & safety</a><a href="#workspace" onClick={() => setMenuOpen(false)}>Workspace</a></div>
      <div className="nav-actions"><button className="theme-toggle" aria-label="Toggle color theme" onClick={() => setDark((value) => !value)}><span className="sun">☼</span><span className="moon">◐</span></button><a className="text-button" href="#workspace">Sign in</a><a className="nav-cta" href="#workspace">Open workspace <span>↗</span></a><button className="menu-button" aria-label="Toggle menu" onClick={() => setMenuOpen((value) => !value)}>☰</button></div>
    </nav>
    <main>
      <section className="hero">
        <div className="hero-copy"><div className="pill"><span className="status-dot" /> Weather intelligence for the real world</div><h1>Make every move<br /><em>weather-aware.</em></h1><p className="hero-lede">WeatherOps turns live weather, location context, and transparent decision logic into one clear operational call.</p><div className="hero-actions"><a className="primary-button" href="#workspace">Run an analysis <span>↗</span></a><a className="secondary-button" href="#platform"><span className="play-icon">▶</span> Explore the platform</a></div><div className="hero-proof"><div className="avatars"><span>AN</span><span>RS</span><span>DK</span><span>+</span></div><p><strong>Built for teams in motion</strong><br /><span>From field ops to critical planning</span></p></div></div>
        <div className="hero-visual" aria-label="WeatherOps operational overview"><div className="visual-glow" /><div className="orbital orbital-one" /><div className="orbital orbital-two" /><div className="orbital orbital-three" /><div className="visual-header"><span className="mini-brand"><span className="brand-mark small"><span>W</span></span> weatherops</span><span className="live-label"><i /> Live conditions</span></div><div className="radar"><div className="radar-sweep" /><div className="radar-ring ring-a" /><div className="radar-ring ring-b" /><div className="radar-ring ring-c" /><span className="radar-point p1" /><span className="radar-point p2" /><span className="radar-point p3" /><span className="radar-point p4" /><div className="radar-center"><strong>92</strong><span>readiness score</span></div></div><div className="visual-footer"><span>▣ &nbsp; Jakarta, ID</span><span>Updated just now &nbsp; ↗</span></div></div>
      </section>
      <section className="trust-strip" id="trust"><span>ONE SYSTEM FOR</span><div><strong>FIELD OPERATIONS</strong><strong>LOGISTICS</strong><strong>EVENTS</strong><strong>INFRASTRUCTURE</strong><strong>AGRICULTURE</strong></div></section>
      <section className="section intro" id="platform"><div className="section-kicker">01 / THE WEATHEROPS WAY</div><div className="intro-grid"><h2>Clarity when<br /><span>conditions change.</span></h2><div><p className="section-lede">Most weather data tells you what is happening. WeatherOps helps your team decide what to do next—with evidence you can understand and act on.</p><a className="inline-link" href="#how-it-works">See how it works <span>→</span></a></div></div><div className="feature-grid"><article className="feature-card featured"><span className="feature-number">01</span><div className="feature-icon blue">✦</div><h3>One operational truth</h3><p>Bring forecasts, hazard context, and local geography into a single decision surface.</p><a href="#workspace">Explore analysis <span>↗</span></a><div className="card-lines" /></article><article className="feature-card"><span className="feature-number">02</span><div className="feature-icon purple">⌁</div><h3>Decisions with receipts</h3><p>Every recommendation is traceable to evidence, confidence, and a clear time window.</p><a href="#trust">Our methodology <span>↗</span></a></article><article className="feature-card"><span className="feature-number">03</span><div className="feature-icon green">◌</div><h3>Ready for the field</h3><p>Simple outputs for teams that need a confident go, mitigate, defer, or stop.</p><a href="#workspace">Open workspace <span>↗</span></a></article></div></section>
      <section className="section workflow" id="how-it-works"><div className="workflow-copy"><div className="section-kicker">02 / FROM SIGNAL TO ACTION</div><h2>A calmer way to<br /><span>move forward.</span></h2><p className="section-lede">Make operational weather part of your workflow, not another tab your team has to interpret.</p><div className="steps"><div className="step active"><b>01</b><span><strong>Set the context</strong><small>Choose your exact location, activity, and time window.</small></span></div><div className="step"><b>02</b><span><strong>Read the conditions</strong><small>See live hazard signals and local forecast evidence.</small></span></div><div className="step"><b>03</b><span><strong>Make the call</strong><small>Share a clear decision with your team.</small></span></div></div></div><div className="decision-preview"><div className="preview-top"><span>DECISION BRIEF</span><span className="preview-live"><i /> CURRENT</span></div><div className="preview-location"><span className="location-pin">⌖</span><div><strong>Jakarta Selatan</strong><small>Today · 14:00—16:00</small></div></div><div className="decision-score"><div className="score-ring"><strong>72</strong><small>/ 100</small></div><div><span className="decision-tag">PROCEED WITH MITIGATION</span><p>Conditions are workable. Monitor rainfall intensity before mobilizing.</p></div></div><div className="preview-bars"><span><i style={{width:'78%'}} /> Rainfall</span><span><i style={{width:'42%'}} /> Wind</span><span><i style={{width:'25%'}} /> Visibility</span></div><div className="preview-foot"><span>Confidence <strong>HIGH</strong></span><span>3 evidence sources</span></div></div></section>
      <section className="workspace-section" id="workspace"><div className="workspace-head"><div><div className="section-kicker">03 / YOUR OPERATIONAL WORKSPACE</div><h2>Start with a<br /><span>place and a plan.</span></h2></div><p>Select a location to explore the operational map. WeatherOps keeps the map as input and visualization—the backend remains the authority for every score.</p></div><LocationPickerMap onSelect={setPicked} />{picked && <p className="selected">Location selected: <strong>{picked.fullName}</strong> · {picked.code}</p>}<TrackingMap analyses={demo} /></section>
      <section className="final-cta"><div className="section-kicker">WEATHEROPS / 2026</div><h2>Better decisions<br /><em>start here.</em></h2><p>Bring weather intelligence into the moments that matter.</p><a className="primary-button" href="#workspace">Enter the workspace <span>↗</span></a></section>
    </main>
    <footer><a className="brand" href="#"><span className="brand-mark"><span>W</span></span><span>weather<span className="brand-muted">ops</span></span></a><span>Operational clarity, wherever the weather takes you.</span><span>© 2026 WeatherOps</span></footer>
  </div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);